### ISSUE TITLE
.Net Core 2.2 =>Runtime Error :Method not found

### ISSUE THREAD

**Issue by MasallahOZEN** [phatboyg/GreenPipes#25]
Hi, with latest masstransit + rabbitmq client I get this error.

Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.

![image](https://user-images.githubusercontent.com/811777/53474723-e7c13500-3a7e-11e9-9b4f-e150acd3cb6a.png)

**Comment by phatboyg** [comment]
I use it extensively with .NET Core 2.2, so I'm not sure what you're seeing. Do you have an example case that breaks, and on which OS?

**Comment by franchyd** [comment]
I am hitting this error on a .netcore 3.0 Webjob running on Azure.
Running:
- MassTransit 5.5.6
- MassTransit.NLog 5.5.6
- MassTransit.RabbitMQ 5.5.6

**Comment by franchyd** [comment]
Update:  I had switched from Framework to .NEt Core, and apparently the GreenPipes dll's are the exact same size in bytes in framework and .net standard.   MSDeploy by default apparently uses file size to determine if any changes have been made.  I had too add the -useCheckSum flag to get it to properly replace the old .net framework dll with the new .net standard one.  So to anyone experiencing this same issue.  The likely culprit is your deployment process because it indicates the wrong GreenPipes dll is being used
